package Aurora::Context::Connection;
use strict;

use Socket;
use Aurora::Log;
use Aurora::Exception qw/:try/;


sub new {
  my ($class, $ip) = @_;
  my ($self);
  $self = bless {
		 ip   => $ip,
		 host => undef,
		 user => undef,
		}, $class;
  return $self;
}

sub ip {
  my ($self) = @_;
  return $self->{ip};
}

sub host {
  my ($self) = @_;
  unless (defined $self->{host}) {
    $self->{host} = gethostbyaddr(inet_aton($self->{ip}), AF_INET);
  }
  return $self->{host};
}

sub user {
  my ($self, $user) = @_;
  $self->{user} = $user if defined $user;
  return $self->{user};
}

1;

__END__

=pod

=head1 NAME

Aurora::Context::Connection - Connection information for the current
remote client.


=head1 SYNOPSIS

  use Aurora::Context::Connection;

  $connection = Aurora::Context::Connection->new('127.0.0.1');

  $ip = $connection->ip;
  $host = $connection->host;
  $user = $connection->user;

=head1 DESCRIPTION

This object provides the current information about the connection to
the remote client.

=head1 CONSTRUCTOR

=over 1

=item B<new>($ip_addr)

Constructs a new Aurora Context Connection object. The constructor
accepts a string containing the remote IP address of the client.

=back

=head1 ACCESSOR METHODS

=over 3

=item B<ip>()

Returns the remote IP address of the client.

=item B<host>()

Returns the remote hostname of the client.

=item B<user>([$user])

When supplied with a user identifier (as generated by a seperate
authentication system), this methods sets the user for this
connection, otherwise this method returns the current user identifier
that has been set.

=back

=head1 AUTHOR/LICENCE

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston,
MA  02111-1307, USA.

(c)2001-2004 Darren Graves (darren@iterx.org), All Rights Reserved.

=head1 SEE ALSO

L<Aurora>, L<Aurora::Context>

